name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am JST on Monday
    - cron: "0 15 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
